### ISSUE TITLE
response.headers['Content-Type'] ="text/html;"  return  Content-Type: text/plain

### ISSUE THREAD

**Issue by tablecell** [pete/watts#4]
```
require 'watts'

class Simple < Watts::App
	class EZResource < Watts::Resource
	
		get { 
		response.headers['Content-Type'] ="text/html;charset=utf-8"

		#"Hello, World!\n" 
		ERB.new(File.read("view/test.erb")).result
		
		}
	end

	resource('/', EZResource)
end

```
curl http://localhost:9292/
 HTTP/1.1 200 OK
 Content-Type: text/plain
 Content-Length: 14

**Comment by mustmodify** [comment]
@pete I'm also having this issue... any thoughts?

**Comment by mustmodify** [comment]
This works, but it's a suboptimal interface IMO

```
  class BookDropResource < Watts::Resource
    get {
      [
        200,
        {'Content-Type' => 'text/html'},
        [ERB.new(File.read("#{__dir__}/views/book_drop_index.html.erb")).result]
      ]
    }
  end

**Comment by mustmodify** [comment]
https://github.com/pete/watts/pull/5

**Comment by pete** [comment]
@mustmodify I made a note in PR #5, but so it's here as well, I think it'd be reasonable to do something like an instance method that provides a default `Content-Type`.  The only reservations I'd have about that are that if you try to handle `Accept` properly, it is more likely to get in the way than help.  I'm not enamored of Rack's `[code,{headers},[body]]` format, but it seems reasonable to stick close to Rack unless there's a reason.
